'use strict';

const esc = (v) => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&apos;','"':'&quot;'})[c]);
const colors = ['#79D9FF','#8B9CFF','#B6F3FF','#A9B7CA','#6FE8C8'];

function frame(id, eyebrow, code, content, height=500) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="${height}" viewBox="0 0 1200 ${height}" role="img" aria-labelledby="${id}-title ${id}-desc">
  <title id="${id}-title">${esc(eyebrow)}</title><desc id="${id}-desc">Minimal science-fiction interface for AMIRGH23.</desc>
  <defs>
    <linearGradient id="${id}-wash" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#0C1624"/><stop offset=".58" stop-color="#050811"/><stop offset="1" stop-color="#0A1020"/></linearGradient>
    <radialGradient id="${id}-light"><stop stop-color="#79D9FF" stop-opacity=".16"/><stop offset="1" stop-color="#79D9FF" stop-opacity="0"/></radialGradient>
    <filter id="${id}-soft" x="-40%" y="-40%" width="180%" height="180%"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
    <style>.sans{font-family:Inter,'Segoe UI',Arial,sans-serif}.mono{font-family:'SFMono-Regular',Consolas,'Liberation Mono',monospace}.ice{fill:#F2FAFF}.blue{fill:#79D9FF}.soft{fill:#91A2B8}.faint{fill:#526176}.mint{fill:#6FE8C8}.label{font-size:11px;letter-spacing:2.6px}.micro{font-size:10px}.pulse{animation:${id}Pulse 3.2s ease-in-out infinite}@keyframes ${id}Pulse{50%{opacity:.3}}@media(prefers-reduced-motion:reduce){*{animation:none!important}}</style>
  </defs>
  <rect width="1200" height="${height}" rx="18" fill="url(#${id}-wash)"/><rect x=".75" y=".75" width="1198.5" height="${height-1.5}" rx="17" fill="none" stroke="#8ACBE8" stroke-opacity=".26" stroke-width="1.5"/>
  <circle cx="1060" cy="115" r="230" fill="url(#${id}-light)"/><path d="M38 67H1162" stroke="#A4B8CA" stroke-opacity=".12"/><circle cx="38" cy="35" r="3" fill="#6FE8C8"/><text x="53" y="39" class="mono soft label">${esc(eyebrow)}</text><text x="1162" y="39" text-anchor="end" class="mono faint micro">${esc(code)}</text>
  ${content}</svg>`;
}

function hero(){return frame('hero','AMIRGH23 / NEURAL NEXUS','INTERFACE 03 — ONLINE',`
  <g class="sans"><text x="64" y="132" class="mono mint label">AUTONOMOUS INTELLIGENCE SYSTEMS</text><text x="60" y="232" class="ice" font-size="78" font-weight="650" letter-spacing="-2">AMIRGH23</text><text x="63" y="282" class="blue" font-size="25" font-weight="500" letter-spacing="9">NEURAL NEXUS</text><text x="63" y="334" class="soft" font-size="18">AI &amp; Robotics · Agents · Learning Systems · Intelligent Interfaces</text><text x="63" y="375" class="faint" font-size="14">Engineering intelligence beyond the demo.</text></g>
  <g transform="translate(63 411)" class="mono"><rect width="468" height="52" rx="8" fill="#0B1220" stroke="#79D9FF" stroke-opacity=".28"/><text x="18" y="32" class="ice" font-size="13">THE FUTURE IS ENGINEERED.</text><circle cx="437" cy="26" r="5" fill="#6FE8C8" class="pulse"/></g>
  <g transform="translate(886 255)"><circle r="151" fill="#07101B" stroke="#79D9FF" stroke-opacity=".2"/><circle r="114" fill="none" stroke="#AFC7D8" stroke-opacity=".18"/><circle r="79" fill="none" stroke="#79D9FF" stroke-opacity=".46"/><circle r="38" fill="#79D9FF" fill-opacity=".1" stroke="#B6F3FF"/><circle r="10" fill="#B6F3FF" filter="url(#hero-soft)"/><g stroke="#79D9FF" stroke-opacity=".28"><path d="M-180 0h101M79 0h101M0-180v101M0 79v101"/></g><g fill="#6FE8C8"><circle cx="-114" r="4"/><circle cx="114" r="4"/></g></g>
  <g class="mono faint micro"><text x="1048" y="440">CORE SYNC</text><text x="1048" y="459" class="ice">94.0%</text></g>`,500)}

function identity(){return frame('identity','AUTHORIZED OPERATOR','IDENTITY / 87558156',`
  <g transform="translate(54 94)"><rect width="315" height="300" rx="22" fill="#08111D" stroke="#79D9FF" stroke-opacity=".28"/><circle cx="157" cy="112" r="50" fill="#0D1826" stroke="#91A2B8"/><path d="M75 253c12-77 152-77 164 0" fill="#0D1826" stroke="#91A2B8"/><path d="M34 42h32M34 42v32M281 42h-32M281 42v32M34 258h32M34 258v-32M281 258h-32M281 258v-32" fill="none" stroke="#79D9FF" stroke-opacity=".6"/><text x="157" y="280" text-anchor="middle" class="mono mint micro">BIOMETRIC LINK VERIFIED</text></g>
  <g transform="translate(425 102)" class="sans"><text class="mono blue label">OPERATOR 01</text><text y="57" class="ice" font-size="36" font-weight="600">Amirreza Ghaffarian</text><text y="91" class="soft" font-size="17">Autonomous Intelligence Architect</text><text y="135" class="faint" font-size="14">Building systems that retrieve, learn, perceive and act.</text>
  <g transform="translate(0 174)" class="mono"><g><text class="faint micro">CODENAME</text><text y="25" class="ice" font-size="14">AMIRGH23</text></g><g transform="translate(270 0)"><text class="faint micro">STATUS</text><text y="25" class="mint" font-size="14">● OPERATIONAL</text></g><g transform="translate(0 68)"><text class="faint micro">SPECIALIZATION</text><text y="25" class="ice" font-size="14">LLM / RAG / AGENTS / RL</text></g><g transform="translate(270 68)"><text class="faint micro">LOCATION</text><text y="25" class="ice" font-size="14">MASHHAD / IRAN</text></g></g></g>`,440)}

function skills(){const a=[['LLM ENGINEERING',86,'Transformers and local inference'],['AGENT SYSTEMS',82,'Tools, memory and orchestration'],['RAG ARCHITECTURE',81,'Retrieval and grounded answers'],['LOCAL AI',76,'Private GPU model serving'],['COMPUTER VISION',72,'VLM, OCR and perception'],['FULL-STACK SYSTEMS',84,'React, TypeScript and APIs'],['MODEL TRAINING',70,'Adaptation and validation'],['AI INFRASTRUCTURE',73,'Containers and observability'],['AUTOMATION',80,'Reliable delivery workflows'],['SECURITY RESEARCH',62,'Threat-aware system design']];const cards=a.map(([n,l,d],i)=>{const x=42+(i%2)*558,y=86+Math.floor(i/2)*103;return `<g transform="translate(${x} ${y})" class="mono"><rect width="516" height="84" rx="12" fill="#08111D" stroke="#8EA9BA" stroke-opacity=".16"/><text x="18" y="27" class="ice" font-size="14">${n}</text><text x="496" y="27" text-anchor="end" class="blue" font-size="12">${l}</text><text x="18" y="50" class="faint micro">${d}</text><rect x="18" y="66" width="478" height="3" rx="2" fill="#192535"/><rect x="18" y="66" width="${l*4.78}" height="3" rx="2" fill="${colors[i%colors.length]}"/></g>`}).join('');return frame('skills','CAPABILITY INDEX','10 ACTIVE MODULES',cards,620)}

function network(){const names=['VISION','RAG','CODE','SECURITY','MEMORY','MCP','OCR','QDRANT','AGENTS','TOOLS'],p=[[185,135],[398,95],[802,95],[1015,135],[1070,280],[1015,425],[802,465],[398,465],[185,425],[130,280]];const lines=p.map(([x,y])=>`<path d="M600 280L${x} ${y}"/>`).join('');const nodes=names.map((n,i)=>`<g transform="translate(${p[i][0]} ${p[i][1]})" class="mono"><circle r="44" fill="#08111D" stroke="#79D9FF" stroke-opacity=".3"/><text y="-2" text-anchor="middle" class="ice" font-size="12">${n}</text><text y="17" text-anchor="middle" class="mint" font-size="8">ONLINE</text></g>`).join('');return frame('network','SYSTEM TOPOLOGY','10 CONNECTED NODES',`<g fill="none" stroke="#79D9FF" stroke-opacity=".16">${lines}</g><g transform="translate(600 280)"><circle r="91" fill="#07101B" stroke="#79D9FF" stroke-opacity=".5"/><circle r="65" fill="none" stroke="#91A2B8" stroke-opacity=".25"/><text y="-4" text-anchor="middle" class="mono ice" font-size="15">AMIRGH23</text><text y="19" text-anchor="middle" class="mono mint micro">CORE ONLINE</text></g>${nodes}`,560)}

function project({id,name,type,description,tech,status='OPEN'}){return frame(`project-${id.replace(/\W/g,'').toLowerCase()}`,type,id,`<g transform="translate(54 94)" class="sans"><text class="mono mint label">${esc(status)}</text><text y="53" class="ice" font-size="32" font-weight="600">${esc(name)}</text><text y="91" class="soft" font-size="15">${esc(description)}</text><g transform="translate(0 126)" class="mono"><rect width="700" height="42" rx="8" fill="#08111D" stroke="#79D9FF" stroke-opacity=".2"/><text x="16" y="26" class="blue micro">${esc(tech)}</text></g><text y="212" class="mono ice" font-size="12">ACCESS REPOSITORY →</text></g><g transform="translate(1015 181)"><circle r="76" fill="#07101B" stroke="#79D9FF" stroke-opacity=".36"/><circle r="53" fill="none" stroke="#91A2B8" stroke-opacity=".2"/><text y="5" text-anchor="middle" class="mono ice" font-size="15">${esc(id)}</text></g>`,310)}

function footer(){return frame('footer','NEURAL NEXUS','CHANNEL REMAINS OPEN',`<g text-anchor="middle" class="sans"><text x="600" y="118" class="ice" font-size="30" font-weight="560">Continue beyond the profile.</text><text x="600" y="157" class="soft" font-size="15">Explore the interactive system, complete repository network and live intelligence core.</text><g transform="translate(466 191)" class="mono"><rect width="268" height="48" rx="9" fill="#79D9FF" fill-opacity=".09" stroke="#79D9FF" stroke-opacity=".42"/><text x="134" y="30" text-anchor="middle" class="blue" font-size="12">ENTER NEURAL NEXUS →</text></g><text x="600" y="270" class="faint micro">AMIRGH23 / SYSTEM ONLINE</text></g>`,300)}

function header(number,title,detail){const id=`header-${number}`;return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="112" viewBox="0 0 1200 112" role="img" aria-labelledby="${id}-title ${id}-desc"><title id="${id}-title">${esc(number)} ${esc(title)}</title><desc id="${id}-desc">${esc(detail)}</desc><defs><linearGradient id="${id}-line"><stop stop-color="#79D9FF"/><stop offset=".72" stop-color="#79D9FF" stop-opacity=".12"/><stop offset="1" stop-color="#79D9FF" stop-opacity="0"/></linearGradient><style>.sans{font-family:Inter,'Segoe UI',Arial,sans-serif}.mono{font-family:'SFMono-Regular',Consolas,'Liberation Mono',monospace}</style></defs><rect width="1200" height="112" rx="14" fill="#07101B"/><rect x=".75" y=".75" width="1198.5" height="110.5" rx="13" fill="none" stroke="#9CC9DC" stroke-opacity=".18"/><rect x="26" y="24" width="64" height="64" rx="12" fill="#79D9FF" fill-opacity=".08" stroke="#79D9FF" stroke-opacity=".28"/><text x="58" y="64" text-anchor="middle" class="mono" fill="#79D9FF" font-size="16">${esc(number)}</text><text x="119" y="54" class="sans" fill="#F2FAFF" font-size="24" font-weight="560" letter-spacing=".7">${esc(title)}</text><text x="120" y="78" class="mono" fill="#71849A" font-size="10" letter-spacing="1.5">${esc(detail)}</text><path d="M720 56H1165" stroke="url(#${id}-line)"/><circle cx="1165" cy="56" r="4" fill="#6FE8C8"/><circle cx="1165" cy="56" r="9" fill="none" stroke="#6FE8C8" stroke-opacity=".2"/></svg>`}

function activity(profile,data){const rows=[['LATEST REPOSITORY',data.latest.name],['PUBLIC REPOSITORIES',data.user.public_repos],['NETWORK',`${data.user.followers} followers · ${data.stars} stars`],['PRIMARY LANGUAGES',data.languages.join(' / ')||'Unclassified'],['LAST PUSH',new Date(data.latest.pushed_at).toISOString().slice(0,16).replace('T',' ')+' UTC']];const body=rows.map(([k,v],i)=>`<g transform="translate(50 ${91+i*66})" class="mono"><rect width="1100" height="50" rx="9" fill="#08111D" fill-opacity="${i%2?'.72':'1'}"/><text x="18" y="30" class="faint micro">${esc(k)}</text><text x="1078" y="30" text-anchor="end" class="ice" font-size="13">${esc(v)}</text></g>`).join('');return frame('activity','LIVE SIGNAL','PUBLIC GITHUB DATA',body,455)}

function neural(profile,data){const a=[['CORE SYNC','94%'],['PUBLIC NODES',data.user.public_repos],['VECTOR MEMORY',`${data.user.public_repos} repositories`],['SECURITY',profile.securityStatus],['MODEL ROUTER','Operational'],['COMPUTE',profile.computeNode]];const body=a.map(([n,v],i)=>{const x=42+(i%3)*372,y=92+Math.floor(i/3)*156;return `<g transform="translate(${x} ${y})" class="mono"><rect width="334" height="126" rx="14" fill="#08111D" stroke="#8EA9BA" stroke-opacity=".16"/><text x="18" y="30" class="faint micro">${esc(n)}</text><text x="18" y="69" class="ice" font-size="17">${esc(v)}</text><circle cx="300" cy="28" r="4" fill="#6FE8C8"/><rect x="18" y="93" width="298" height="3" fill="#192535"/><rect x="18" y="93" width="${205+i*13}" height="3" fill="${colors[i%colors.length]}"/></g>`}).join('');return frame('core','SYSTEM TELEMETRY','LIVE CONFIGURATION',body,425)}

module.exports={hero,identity,skills,network,project,footer,header,activity,neural};
