'use strict';

const esc = (v) => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&apos;','"':'&quot;'})[c]);
const colors = ['#00F7FF','#FF2BD6','#8B5CF6','#FF7AE5','#39FF14'];

function frame(id, eyebrow, code, content, height=500) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="${height}" viewBox="0 0 1200 ${height}" role="img" aria-labelledby="${id}-title ${id}-desc">
  <title id="${id}-title">${esc(eyebrow)}</title><desc id="${id}-desc">Retro-neon arcade interface for AMIRGH23.</desc>
  <defs>
    <linearGradient id="${id}-wash" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#16082B"/><stop offset=".48" stop-color="#050510"/><stop offset="1" stop-color="#07192A"/></linearGradient>
    <linearGradient id="${id}-neon" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#FF2BD6"/><stop offset=".5" stop-color="#8B5CF6"/><stop offset="1" stop-color="#00F7FF"/></linearGradient>
    <radialGradient id="${id}-light"><stop stop-color="#FF2BD6" stop-opacity=".2"/><stop offset=".48" stop-color="#8B5CF6" stop-opacity=".09"/><stop offset="1" stop-color="#00F7FF" stop-opacity="0"/></radialGradient>
    <pattern id="${id}-grid" width="54" height="28" patternUnits="userSpaceOnUse"><path d="M54 0H0V28" fill="none" stroke="#00F7FF" stroke-opacity=".08"/></pattern>
    <filter id="${id}-soft" x="-40%" y="-40%" width="180%" height="180%"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
    <style>.sans{font-family:Inter,'Segoe UI',Arial,sans-serif}.mono{font-family:'SFMono-Regular',Consolas,'Liberation Mono',monospace}.ice{fill:#FFF7FF}.blue{fill:#00F7FF}.soft{fill:#B8B5D1}.faint{fill:#77738F}.mint{fill:#FF2BD6}.label{font-size:11px;letter-spacing:2.6px}.micro{font-size:10px}.pulse{animation:${id}Pulse 3.2s ease-in-out infinite}@keyframes ${id}Pulse{50%{opacity:.3}}@media(prefers-reduced-motion:reduce){*{animation:none!important}}</style>
  </defs>
  <rect width="1200" height="${height}" rx="18" fill="url(#${id}-wash)"/><rect y="${Math.max(72,height-150)}" width="1200" height="${Math.min(150,height-72)}" fill="url(#${id}-grid)"/><rect x=".75" y=".75" width="1198.5" height="${height-1.5}" rx="17" fill="none" stroke="url(#${id}-neon)" stroke-opacity=".58" stroke-width="1.5"/>
  <rect x="1" y="1" width="5" height="${height-2}" rx="3" fill="url(#${id}-neon)"/><circle cx="1060" cy="115" r="230" fill="url(#${id}-light)"/><path d="M38 67H1162" stroke="url(#${id}-neon)" stroke-opacity=".28"/><circle cx="38" cy="35" r="3" fill="#FF2BD6" filter="url(#${id}-soft)"/><text x="53" y="39" class="mono soft label">${esc(eyebrow)}</text><text x="1162" y="39" text-anchor="end" class="mono faint micro">${esc(code)}</text>
  ${content}</svg>`;
}

function hero(){return frame('hero','AMIRGH23 / NEURAL NEXUS','INTERFACE 03 — ONLINE',`
  <g class="sans"><text x="64" y="132" class="mono mint label">AUTONOMOUS INTELLIGENCE SYSTEMS</text><text x="60" y="232" class="ice" font-size="78" font-weight="650" letter-spacing="-2">AMIRGH23</text><text x="63" y="282" class="blue" font-size="25" font-weight="500" letter-spacing="9">NEURAL NEXUS</text><text x="63" y="334" class="soft" font-size="18">AI &amp; Robotics · Agents · Learning Systems · Intelligent Interfaces</text><text x="63" y="375" class="faint" font-size="14">Engineering intelligence beyond the demo.</text></g>
  <g transform="translate(63 411)" class="mono"><rect width="468" height="52" rx="8" fill="#0B0718" stroke="#00F7FF" stroke-opacity=".52"/><path d="M0 0h155" stroke="#FF2BD6" stroke-width="2"/><text x="18" y="32" class="ice" font-size="13">THE FUTURE IS ENGINEERED.</text><circle cx="437" cy="26" r="5" fill="#FF2BD6" class="pulse" filter="url(#hero-soft)"/></g>
  <g transform="translate(886 255)"><circle r="151" fill="#080615" stroke="#FF2BD6" stroke-opacity=".45"/><circle r="114" fill="none" stroke="#8B5CF6" stroke-opacity=".55"/><circle r="79" fill="none" stroke="#00F7FF" stroke-opacity=".78"/><circle r="38" fill="#FF2BD6" fill-opacity=".12" stroke="#FF7AE5"/><circle r="10" fill="#00F7FF" filter="url(#hero-soft)"/><g stroke="#00F7FF" stroke-opacity=".38"><path d="M-180 0h101M79 0h101M0-180v101M0 79v101"/></g><g fill="#FF2BD6"><circle cx="-114" r="4"/><circle cx="114" r="4"/></g></g>
  <g class="mono faint micro"><text x="1048" y="440">CORE SYNC</text><text x="1048" y="459" class="ice">94.0%</text></g>`,500)}

function identity(){return frame('identity','AUTHORIZED OPERATOR','IDENTITY / 87558156',`
  <g transform="translate(54 94)"><rect width="315" height="300" rx="22" fill="#0B0718" stroke="#00F7FF" stroke-opacity=".58"/><path d="M0 28V0h28M287 0h28v28M0 272v28h28M287 300h28v-28" fill="none" stroke="#FF2BD6" stroke-width="2"/><circle cx="157" cy="112" r="50" fill="#140A26" stroke="#8B5CF6"/><path d="M75 253c12-77 152-77 164 0" fill="#140A26" stroke="#8B5CF6"/><path d="M34 42h32M34 42v32M281 42h-32M281 42v32M34 258h32M34 258v-32M281 258h-32M281 258v-32" fill="none" stroke="#00F7FF" stroke-opacity=".8"/><text x="157" y="280" text-anchor="middle" class="mono mint micro">BIOMETRIC LINK VERIFIED</text></g>
  <g transform="translate(425 102)" class="sans"><text class="mono blue label">OPERATOR 01</text><text y="57" class="ice" font-size="36" font-weight="600">Amirreza Ghaffarian</text><text y="91" class="soft" font-size="17">Autonomous Intelligence Architect</text><text y="135" class="faint" font-size="14">Building systems that retrieve, learn, perceive and act.</text>
  <g transform="translate(0 174)" class="mono"><g><text class="faint micro">CODENAME</text><text y="25" class="ice" font-size="14">AMIRGH23</text></g><g transform="translate(270 0)"><text class="faint micro">STATUS</text><text y="25" class="mint" font-size="14">● OPERATIONAL</text></g><g transform="translate(0 68)"><text class="faint micro">SPECIALIZATION</text><text y="25" class="ice" font-size="14">LLM / RAG / AGENTS / RL</text></g><g transform="translate(270 68)"><text class="faint micro">LOCATION</text><text y="25" class="ice" font-size="14">MASHHAD / IRAN</text></g></g></g>`,440)}

function skills(){const a=[['LLM ENGINEERING',86,'Transformers and local inference'],['AGENT SYSTEMS',82,'Tools, memory and orchestration'],['RAG ARCHITECTURE',81,'Retrieval and grounded answers'],['LOCAL AI',76,'Private GPU model serving'],['COMPUTER VISION',72,'VLM, OCR and perception'],['FULL-STACK SYSTEMS',84,'React, TypeScript and APIs'],['MODEL TRAINING',70,'Adaptation and validation'],['AI INFRASTRUCTURE',73,'Containers and observability'],['AUTOMATION',80,'Reliable delivery workflows'],['SECURITY RESEARCH',62,'Threat-aware system design']];const cards=a.map(([n,l,d],i)=>{const x=42+(i%2)*558,y=86+Math.floor(i/2)*103;return `<g transform="translate(${x} ${y})" class="mono"><rect width="516" height="84" rx="12" fill="#0B0718" stroke="${colors[i%3]}" stroke-opacity=".3"/><path d="M0 18V0h18" fill="none" stroke="${colors[(i+1)%3]}"/><text x="18" y="27" class="ice" font-size="14">${n}</text><text x="496" y="27" text-anchor="end" class="blue" font-size="12">${l}</text><text x="18" y="50" class="faint micro">${d}</text><rect x="18" y="66" width="478" height="3" rx="2" fill="#241633"/><rect x="18" y="66" width="${l*4.78}" height="3" rx="2" fill="${colors[i%colors.length]}"/></g>`}).join('');return frame('skills','CAPABILITY INDEX','10 ACTIVE MODULES',cards,620)}

function network(){const names=['VISION','RAG','CODE','SECURITY','MEMORY','MCP','OCR','QDRANT','AGENTS','TOOLS'],p=[[185,135],[398,95],[802,95],[1015,135],[1070,280],[1015,425],[802,465],[398,465],[185,425],[130,280]];const lines=p.map(([x,y])=>`<path d="M600 280L${x} ${y}"/>`).join('');const nodes=names.map((n,i)=>`<g transform="translate(${p[i][0]} ${p[i][1]})" class="mono"><circle r="44" fill="#0B0718" stroke="${colors[i%3]}" stroke-opacity=".58"/><circle r="39" fill="none" stroke="${colors[(i+1)%3]}" stroke-opacity=".16"/><text y="-2" text-anchor="middle" class="ice" font-size="12">${n}</text><text y="17" text-anchor="middle" class="mint" font-size="8">ONLINE</text></g>`).join('');return frame('network','SYSTEM TOPOLOGY','10 CONNECTED NODES',`<g fill="none" stroke="#00F7FF" stroke-opacity=".26">${lines}</g><g transform="translate(600 280)"><circle r="91" fill="#080615" stroke="#FF2BD6" stroke-opacity=".74"/><circle r="65" fill="none" stroke="#00F7FF" stroke-opacity=".62"/><circle r="55" fill="#8B5CF6" fill-opacity=".08"/><text y="-4" text-anchor="middle" class="mono ice" font-size="15">AMIRGH23</text><text y="19" text-anchor="middle" class="mono mint micro">CORE ONLINE</text></g>${nodes}`,560)}

function project({id,name,type,description,tech,status='OPEN'}){return frame(`project-${id.replace(/\W/g,'').toLowerCase()}`,type,id,`<g transform="translate(54 94)" class="sans"><text class="mono mint label">${esc(status)}</text><text y="53" class="ice" font-size="32" font-weight="600">${esc(name)}</text><text y="91" class="soft" font-size="15">${esc(description)}</text><g transform="translate(0 126)" class="mono"><rect width="700" height="42" rx="8" fill="#0B0718" stroke="#00F7FF" stroke-opacity=".42"/><path d="M0 0h145" stroke="#FF2BD6" stroke-width="2"/><text x="16" y="26" class="blue micro">${esc(tech)}</text></g><text y="212" class="mono ice" font-size="12">ACCESS REPOSITORY →</text></g><g transform="translate(1015 181)"><circle r="76" fill="#080615" stroke="#FF2BD6" stroke-opacity=".62"/><circle r="53" fill="none" stroke="#00F7FF" stroke-opacity=".48"/><text y="5" text-anchor="middle" class="mono ice" font-size="15">${esc(id)}</text></g>`,310)}

function footer(){return frame('footer','NEURAL NEXUS','CHANNEL REMAINS OPEN',`<g text-anchor="middle" class="sans"><text x="600" y="118" class="ice" font-size="30" font-weight="560">Continue beyond the profile.</text><text x="600" y="157" class="soft" font-size="15">Explore the interactive system, complete repository network and live intelligence core.</text><g transform="translate(466 191)" class="mono"><rect width="268" height="48" rx="9" fill="#8B5CF6" fill-opacity=".12" stroke="#00F7FF" stroke-opacity=".62"/><path d="M0 0h92" stroke="#FF2BD6" stroke-width="2"/><text x="134" y="30" text-anchor="middle" class="blue" font-size="12">ENTER NEURAL NEXUS →</text></g><text x="600" y="270" class="faint micro">AMIRGH23 / SYSTEM ONLINE</text></g>`,300)}

function header(number,title,detail){const id=`header-${number}`;return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="112" viewBox="0 0 1200 112" role="img" aria-labelledby="${id}-title ${id}-desc"><title id="${id}-title">${esc(number)} ${esc(title)}</title><desc id="${id}-desc">Retro neon section header. ${esc(detail)}</desc><defs><linearGradient id="${id}-bg" x1="0" x2="1"><stop stop-color="#16082B"/><stop offset=".5" stop-color="#070512"/><stop offset="1" stop-color="#07192A"/></linearGradient><linearGradient id="${id}-line"><stop stop-color="#FF2BD6"/><stop offset=".48" stop-color="#8B5CF6"/><stop offset="1" stop-color="#00F7FF"/></linearGradient><pattern id="${id}-grid" width="32" height="16" patternUnits="userSpaceOnUse"><path d="M32 0H0V16" fill="none" stroke="#00F7FF" stroke-opacity=".08"/></pattern><filter id="${id}-glow" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="2.5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><style>.sans{font-family:Inter,'Segoe UI',Arial,sans-serif}.mono{font-family:'SFMono-Regular',Consolas,'Liberation Mono',monospace}</style></defs><rect width="1200" height="112" rx="14" fill="url(#${id}-bg)"/><rect x="760" width="440" height="112" rx="14" fill="url(#${id}-grid)"/><rect x=".75" y=".75" width="1198.5" height="110.5" rx="13" fill="none" stroke="url(#${id}-line)" stroke-opacity=".62"/><path d="M1 88V14Q1 1 14 1h188" fill="none" stroke="#FF2BD6" stroke-width="2"/><rect x="26" y="24" width="64" height="64" rx="12" fill="#8B5CF6" fill-opacity=".16" stroke="#00F7FF" stroke-opacity=".66"/><path d="M26 43V24h19M90 69v19H71" fill="none" stroke="#FF2BD6" stroke-width="2"/><text x="58" y="64" text-anchor="middle" class="mono" fill="#00F7FF" font-size="16" filter="url(#${id}-glow)">${esc(number)}</text><text x="119" y="54" class="sans" fill="#FFF7FF" font-size="24" font-weight="600" letter-spacing=".7">${esc(title)}</text><text x="120" y="78" class="mono" fill="#A49FBD" font-size="10" letter-spacing="1.5">${esc(detail)}</text><path d="M720 56H1165" stroke="url(#${id}-line)" stroke-width="1.5"/><circle cx="1165" cy="56" r="4" fill="#FF2BD6" filter="url(#${id}-glow)"/><circle cx="1165" cy="56" r="10" fill="none" stroke="#00F7FF" stroke-opacity=".42"/></svg>`}

function activity(profile,data){const rows=[['LATEST REPOSITORY',data.latest.name],['PUBLIC REPOSITORIES',data.user.public_repos],['NETWORK',`${data.user.followers} followers · ${data.stars} stars`],['PRIMARY LANGUAGES',data.languages.join(' / ')||'Unclassified'],['LAST PUSH',new Date(data.latest.pushed_at).toISOString().slice(0,16).replace('T',' ')+' UTC']];const body=rows.map(([k,v],i)=>`<g transform="translate(50 ${91+i*66})" class="mono"><rect width="1100" height="50" rx="9" fill="#0B0718" fill-opacity="${i%2?'.8':'1'}" stroke="${colors[i%3]}" stroke-opacity=".18"/><rect width="3" height="50" rx="2" fill="${colors[i%3]}"/><text x="18" y="30" class="faint micro">${esc(k)}</text><text x="1078" y="30" text-anchor="end" class="ice" font-size="13">${esc(v)}</text></g>`).join('');return frame('activity','LIVE SIGNAL','PUBLIC GITHUB DATA',body,455)}

function neural(profile,data){const a=[['CORE SYNC','94%'],['PUBLIC NODES',data.user.public_repos],['VECTOR MEMORY',`${data.user.public_repos} repositories`],['SECURITY',profile.securityStatus],['MODEL ROUTER','Operational'],['COMPUTE',profile.computeNode]];const body=a.map(([n,v],i)=>{const x=42+(i%3)*372,y=92+Math.floor(i/3)*156;return `<g transform="translate(${x} ${y})" class="mono"><rect width="334" height="126" rx="14" fill="#0B0718" stroke="${colors[i%3]}" stroke-opacity=".34"/><path d="M0 22V0h22" fill="none" stroke="${colors[(i+1)%3]}" stroke-width="2"/><text x="18" y="30" class="faint micro">${esc(n)}</text><text x="18" y="69" class="ice" font-size="17">${esc(v)}</text><circle cx="300" cy="28" r="4" fill="#FF2BD6"/><rect x="18" y="93" width="298" height="3" fill="#241633"/><rect x="18" y="93" width="${205+i*13}" height="3" fill="${colors[i%colors.length]}"/></g>`}).join('');return frame('core','SYSTEM TELEMETRY','LIVE CONFIGURATION',body,425)}

module.exports={hero,identity,skills,network,project,footer,header,activity,neural};
